# Generated by Django 3.2.6 on 2024-08-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
